# Generated by Django 4.2.1 on 2023-06-06 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_rename_passangers_passanger'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Passanger',
            new_name='Passangers',
        ),
    ]
