# Generated by Django 4.2.1 on 2023-06-07 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0005_rename_passanger_passangers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Passangers',
            new_name='Passanger',
        ),
    ]
