# Generated by Django 4.2.1 on 2023-06-13 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_airport_passenger_alter_flight_destination_and_more'),
        ('flights', '0007_rename_passanger_passenger'),
    ]

    operations = [
    ]
